2. Create a playbook adhoc.yml for configuring repository in all nodes.

   i) Name = baseos
   Description = Baseos Description
   Url = http://content/rhel9.0/x86_64/dvd/BaseOS
   GPG is enabled.
   Gpgkey = http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release
   Repository is enabled.

   ii) Name = appstream
   Description = App Description
   Url = http://content/rhel9.0/x86_64/dvd/AppStream
   GPG is enabled.
   Gpgkey = http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release
   Repository is enabled.

# vim /home/student/ansible/adhoc.yml
---
- name: Creating yum repository
  hosts: all
  tasks:
   - name: Create BaseOS Repository 
     ansible.builtin.yum_repository:
      name: "baseos" 
      description: "Baseos Description" 
      baseurl: http://content/rhel9.0/x86_64/dvd/BaseOS 
      gpgcheck: yes 
      gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release 
      enabled: yes
   - name: Create Appstream Repository
     ansible.builtin.yum_repository: 
      name: "appstream" 
      description: "App Description" 
      baseurl: http://content/rhel9.0/x86_64/dvd/AppStream 
      gpgcheck: yes 
      gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release 
      enabled: yes

# ansible-navigator run adhoc.yml -m stdout

# ansible all -m command -a 'yum repolist all'  #(verify the output)
